name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build tests
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

  platformio-build:
    runs-on: ubuntu-latest
    needs: verify
    strategy:
      fail-fast: false
      matrix:
        board: [esp32dev, esp32-s3-devkitc-1, esp32-c3-devkitm-1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/library.json') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build library examples (ESP32 Arduino)
        run: |
          set -e
          for d in examples/*; do
            if [ -d "$d" ]; then
              echo "Building $d on ${{ matrix.board }} via PlatformIO CI"
              pio ci "$d" \
                --board ${{ matrix.board }} \
                --lib="." \
                --project-option "build_unflags=-std=gnu++11" \
                --project-option "build_flags=-std=gnu++17"
            fi
          done

  arduino-cli:
    runs-on: ubuntu-latest
    needs: verify
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: esp32:esp32:esp32
            name: esp32dev
          - fqbn: esp32:esp32:esp32s3
            name: esp32-s3-devkitc-1
          - fqbn: esp32:esp32:esp32c3
            name: esp32-c3-devkitm-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install libraries
        run: |
          arduino-cli lib update-index
          arduino-cli lib install "ArduinoJson" "StreamUtils"

      - name: Add local library to sketchbook
        run: |
          set -e
          SKETCHBOOK_DIR="${HOME}/Arduino"
          mkdir -p "$SKETCHBOOK_DIR/libraries/ESPJsonDB"
          rsync -a --delete --exclude ".git" ./ "$SKETCHBOOK_DIR/libraries/ESPJsonDB/"

      - name: Build examples (${{ matrix.board.name }})
        env:
          FQBN: ${{ matrix.board.fqbn }}
        run: |
          set -e
          for d in examples/*; do
            if [ -d "$d" ]; then
              echo "Compiling $d"
              arduino-cli compile --fqbn "$FQBN" "$d"
            fi
          done

  create-release:
    runs-on: ubuntu-latest
    needs:
      - verify
      - platformio-build
      - arduino-cli
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
